### ISSUE TITLE
发现2个错别字

### ISSUE THREAD

**Issue by lilifan** [theanarkh/understand-nodejs#1]
第二页倒数第三行 ”所以就打算把这些内容整理成一 **般** 有体系的书，让感兴趣的同学能系统 **能** 去了解nodejs的原理“
应该是 ”所以就打算把这些内容整理成一 **本** 有体系的书，让感兴趣的同学能系统 **地** 去了解nodejs的原理“

另外 ”本书不是nodejs的全部，但是尽量去讲得更多，因为时间关系，不过相信作为nodejs的爱好者，这些不是问题。“  因为时间关系后面感觉不是很通顺

**Comment by theanarkh** [comment]
好，回头我改一下，谢谢！
