### ISSUE TITLE
阅读源码时的一个问题（关于ExternalReference）

### ISSUE THREAD

**Issue by tain335** [theanarkh/understand-nodejs#11]
我发现有些内部模块是需要注册外部引用的
`
NODE_MODULE_CONTEXT_AWARE_INTERNAL(buffer, node::Buffer::Initialize)
NODE_MODULE_EXTERNAL_REFERENCE(buffer, node::Buffer::RegisterExternalReferences)
`

但是有些内部模块就不需要了
`NODE_MODULE_CONTEXT_AWARE_INTERNAL(fs, node::fs::Initialize)`

不知道这是为什么，我查阅了一些文档应该是所有绑定的c++函数都应该注册外部引用，然后从snapshot启动的时候也需要提供这些引用才可以，但是这里源码却有的模块可以不提供，我感觉应该是有些地方还没有注意到，博主能解答一下吗

**Comment by theanarkh** [comment]
看了一下这是新版nodejs引入的，目前还没有研究。

**Comment by theanarkh** [comment]
> 我发现有些内部模块是需要注册外部引用的 `NODE_MODULE_CONTEXT_AWARE_INTERNAL(buffer, node::Buffer::Initialize) NODE_MODULE_EXTERNAL_REFERENCE(buffer, node::Buffer::RegisterExternalReferences)`
> 
> 但是有些内部模块就不需要了 `NODE_MODULE_CONTEXT_AWARE_INTERNAL(fs, node::fs::Initialize)`
> 
> 不知道这是为什么，我查阅了一些文档应该是所有绑定的c++函数都应该注册外部引用，然后从snapshot启动的时候也需要提供这些引用才可以，但是这里源码却有的模块可以不提供，我感觉应该是有些地方还没有注意到，博主能解答一下吗

最近在看这个，现在应该都注册了，这个是为了加速 Node.js 启动，不过是个大工程，你看到的可能不是终态。
