### ISSUE TITLE
为libuv处理网络io实现多线程主从模式是否很有意义呢，redis6 通过多线程实现了一倍的性能提升

### ISSUE THREAD

**Issue by ganshiqingyuan** [theanarkh/understand-nodejs#15]

**Comment by theanarkh** [comment]
说说我的想法，据我的了解，redis6.0网络模型的变化在于把部分网络io交给了io线程处理以利用多核，而传统的模型中是在主线程中同步处理的。如果libuv要支持的话，首先要定义哪些任务交给io线程处理能提高性能，然后把这部分代码作为一个任务交给io线程处理，比如redis里把读取网络io、解析命令放到io线程中做，那libuv估计只能把读取网络io放到io线程，因为libuv是一个框架，对数据的具体处理是上层负责的，这和redis不同，那就看在单线程里串行读取网络io和多线程里并行读取+线程通信+线程切换哪个快了。目前，libuv也有线程池，最多再搞一个io线程池出来，然后像redis一样专门处理网络io。但是性能有没有提升这个就没办法下结论了，欢迎交流。

**Comment by theanarkh** [comment]
> _No description provided._

说说我的想法，据我的了解，redis6.0网络模型的变化在于把部分网络io交给了io线程处理以利用多核，而传统的模型中是在主线程中同步处理的。如果libuv要支持的话，首先要定义哪些任务交给io线程处理能提高性能，然后把这部分代码作为一个任务交给io线程处理，比如redis里把读取网络io、解析命令放到io线程中做，那libuv估计只能把读取网络io放到io线程，因为libuv是一个框架，对数据的具体处理是上层负责的，这和redis不同，那就看在单线程里串行读取网络io和多线程里并行读取+线程通信+线程切换哪个快了。目前，libuv也有线程池，最多再搞一个io线程池出来，然后像redis一样专门处理网络io。但是性能有没有提升这个就没办法下结论了，欢迎交流。

**Comment by theanarkh** [comment]
> 
说说我的想法，据我的了解，redis6.0网络模型的变化在于把部分网络io交给了io线程处理以利用多核，而传统的模型中是在主线程中同步处理的。如果libuv要支持的话，首先要定义哪些任务交给io线程处理能提高性能，然后把这部分代码作为一个任务交给io线程处理，比如redis里把读取网络io、解析命令放到io线程中做，那libuv估计只能把读取网络io放到io线程，因为libuv是一个框架，对数据的具体处理是上层负责的，这和redis不同，那就看在单线程里串行读取网络io和多线程里并行读取+线程通信+线程切换哪个快了。目前，libuv也有线程池，最多再搞一个io线程池出来，然后像redis一样专门处理网络io。但是性能有没有提升这个就没办法下结论了，欢迎交流。

**Comment by ganshiqingyuan** [comment]
> > 
> 
> 说说我的想法，据我的了解，redis6.0网络模型的变化在于把部分网络io交给了io线程处理以利用多核，而传统的模型中是在主线程中同步处理的。如果libuv要支持的话，首先要定义哪些任务交给io线程处理能提高性能，然后把这部分代码作为一个任务交给io线程处理，比如redis里把读取网络io、解析命令放到io线程中做，那libuv估计只能把读取网络io放到io线程，因为libuv是一个框架，对数据的具体处理是上层负责的，这和redis不同，那就看在单线程里串行读取网络io和多线程里并行读取+线程通信+线程切换哪个快了。目前，libuv也有线程池，最多再搞一个io线程池出来，然后像redis一样专门处理网络io。但是性能有没有提升这个就没办法下结论了，欢迎交流。

redis6 和memcache这种纯内存操作的并发极高，在接受完网络io数据后做的事情只是在内存里拿数据，所以在极端情况下单线程接受网络io数据限制了性能上线，多线程主从模式可以获得成倍的提升，nodejs这样做的话虽然不会获得成倍的性能提升，但是肯定能增加单位时间内处理的链接数量（虽然不一定都能完成），，而且貌似只需要在libuv中修改即可（当然接入多线程肯定增加编程复杂性），，目前我了解到的redis6 memcache workflow netty貌似都是这种模型，nodejs也不能落下啊！，奈何我的c水平堪忧，，

**Comment by theanarkh** [comment]
总得来说，就是当有很多数据等待处理的时候，串行处理看起来会比较慢，可以借助多线程多核来提高性能，但是多线程带来的复杂性和开销也是一个问题，可以关注一下社区，或者知乎提问看看业内大佬的想法

**Comment by ganshiqingyuan** [comment]
> 总得来说，就是当有很多数据等待处理的时候，串行处理看起来会比较慢，可以借助多线程多核来提高性能，但是多线程带来的复杂性和开销也是一个问题，可以关注一下社区，或者知乎提问看看业内大佬的想法

哎，到处咨询没人搭理，，你是第一个理我的 = =

**Comment by theanarkh** [comment]
> > 总得来说，就是当有很多数据等待处理的时候，串行处理看起来会比较慢，可以借助多线程多核来提高性能，但是多线程带来的复杂性和开销也是一个问题，可以关注一下社区，或者知乎提问看看业内大佬的想法
> 
> 哎，到处咨询没人搭理，，你是第一个理我的 = =

这个问题本身也是比较复杂的，从理论上也很难证明什么。

**Comment by ganshiqingyuan** [comment]
> > > 总得来说，就是当有很多数据等待处理的时候，串行处理看起来会比较慢，可以借助多线程多核来提高性能，但是多线程带来的复杂性和开销也是一个问题，可以关注一下社区，或者知乎提问看看业内大佬的想法
> > 
> > 
> > 哎，到处咨询没人搭理，，你是第一个理我的 = =
> 
> 这个问题本身也是比较复杂的，从理论上也很难证明什么。

所以说大佬去搞一搞？ 光读懂没意思啊，，改造一下更能推进社区进步，

**Comment by theanarkh** [comment]
> > > > 总得来说，就是当有很多数据等待处理的时候，串行处理看起来会比较慢，可以借助多线程多核来提高性能，但是多线程带来的复杂性和开销也是一个问题，可以关注一下社区，或者知乎提问看看业内大佬的想法
> > > 
> > > 
> > > 哎，到处咨询没人搭理，，你是第一个理我的 = =
> > 
> > 
> > 这个问题本身也是比较复杂的，从理论上也很难证明什么。
> 
> 所以说大佬去搞一搞？ 光读懂没意思啊，，改造一下更能推进社区进步，

没有这时间，也没有这能力，读懂也总比不懂有意思。
