### ISSUE TITLE
Node.js 源码剖析 15-Cluster 有一段没看明白。

### ISSUE THREAD

**Issue by roychen-7** [theanarkh/understand-nodejs#23]
“共享模式实现的核心逻辑主进程在_createServerHandle创建handle时执行bind绑定了地址（但没有listen）。”

在最下面的 “实现自己的 Cluster“中，代码里面不是在主进程里面 listen 的吗？

**Comment by roychen-7** [comment]
感谢指教，谢谢。

**Comment by theanarkh** [comment]
> “共享模式实现的核心逻辑主进程在_createServerHandle创建handle时执行bind绑定了地址（但没有listen）。”
> 
> 在最下面的 “实现自己的 Cluster“中，代码里面不是在主进程里面 listen 的吗？

实现自己的 Cluster 模块中的共享模式，是主进程 _createServerHandle ，没有执行listen，你看的应该是轮询模式？

**Comment by roychen-7** [comment]
> > “共享模式实现的核心逻辑主进程在_createServerHandle创建handle时执行bind绑定了地址（但没有listen）。”
> > 在最下面的 “实现自己的 Cluster“中，代码里面不是在主进程里面 listen 的吗？
> 
> 实现自己的 Cluster 模块中的共享模式，是主进程 _createServerHandle ，没有执行listen，你看的应该是轮询模式？

明白了，我没看仔细，感谢。
