### ISSUE TITLE
请教一下作者nodejs 的network  io和 file io的问题

### ISSUE THREAD

**Issue by SpencerChou** [theanarkh/understand-nodejs#24]
我在Google上也查了很多资料，我看network io是事件循环本身单线程在做的，file io是用线程池在做的，是这样嘛

那network io本身也是用epoll这些函数来处理 io的数据的么，，

我一直没理解polling io中，哪里体现了线程池的概念，我看file io不也是单线程epoll在等待吗？

还有就是network io具体是在那个阶段进行的呢？也是poll io阶段？

如果nodejs是单线程接受网络io，虽然多路复用带来的 并发很高，但是不是还是比不上 netty那种单reactor 多线程的模式，nodejs的网络io处于什么考虑，没有用线程池呢

最后有一句，听说作者在写书，书出来了没

**Comment by theanarkh** [comment]
网络和文件io的回调都在在主线程处理，但是网络io是在主线程poll io(epoll)处理的，文件io是在子线程里处理。

netty 我不了解，我了解的大多数服务器软件的网络 io 都是 reactor + 单线程，比如 nginx、早期的 redis。我理解多线程带来了复杂，也有切换的开销。

书没时间写，开源了。

**Comment by SpencerChou** [comment]
文件io、的部分有源码的讲解嘛，我看的时候好像看poll io阶段就只是 epoll wait

**Comment by SpencerChou** [comment]
书的连接好像打不开

**Comment by theanarkh** [comment]
仓库或pdf里有讲，可以访问了。
