### ISSUE TITLE
nodejs server

### ISSUE THREAD

**Issue by seconp** [theanarkh/understand-nodejs#26]
![1661765430974_CD5FD682-DA90-4718-B8A6-91E0F0D4A15C](https://user-images.githubusercontent.com/32900843/187172777-21e624f6-9303-4ae2-b2a3-2ed669df3d6f.png)

**Comment by zkk123123** [comment]
您好，您的邮件我已收到，谢谢
——张可可

**Comment by theanarkh** [comment]
并发量是说可以同时处理大量的请求，这个其实是事件驱动模块的优势，并不是 Node.js 专属，很多软件都是基于这个架构的。
