### ISSUE TITLE
English translation?

### ISSUE THREAD

**Issue by sidwebworks** [theanarkh/understand-nodejs#27]
Any plans to translate these to other languages, sadly I don't know Chinese otherwise I would've done it already.

But if you allow me and could guide me a little I think I can start a repo translating these docs to English using google translate.

Thank you
@theanarkh

**Comment by theanarkh** [comment]
I don't think it's necessary to translate. It takes a lot of time.

**Comment by sidwebworks** [comment]
@theanarkh I understand, well I love learning about Node core and your writings are one of the best resources I wish I had when initially trying to contribute to Node JS.

I wanted to make it more accessible for others in the community hence I spent my weekend working on this

https://github.com/sidwebworks/understanding-node-core

Would love any feedback or suggestions that you might have. 

Thanks

**Comment by theanarkh** [comment]
Thank you for your efforts. I'll keep an eye on your project. And I will try my best to give some feedback.

**Comment by zkk123123** [comment]
您好，您的邮件我已收到，谢谢
——张可可
