### ISSUE TITLE
请教有关promise和async await协程的问题

### ISSUE THREAD

**Issue by SpencerChou** [theanarkh/understand-nodejs#29]
大佬你好，想请教一下promise 在整个事件循环当中，是在哪个阶段执行的啊。。

事件循环是怎么调度协程的呢？又或者说是生成器，因为有了事件循环我就能够 并发的跑多个for循环在同一个线程中，我发现这是个很好的点，但是 我没能理解他底层是怎么调度的

**Comment by zkk123123** [comment]
您好，您的邮件我已收到，谢谢
——张可可

**Comment by theanarkh** [comment]
事件循环本质是一个循环里不断地处理就绪的任务，Promise 也是其中的一种任务，叫微任务，比如 resolve 的时候就会往微任务里插入一个任务，然后在合适的时机进行处理，最常见的时机就是每次从 C/C++ 层回调 JS 函数之后，这个有点不好理解，需要看一下 Node.js 底层的东西。

**Comment by zkk123123** [comment]
您好，您的邮件我已收到，谢谢
——张可可
