### ISSUE TITLE
[BUG] 官网某些图片未能正确展示

### ISSUE THREAD

**Issue by kirrs** [theanarkh/understand-nodejs#30]
# 概述
图片大小为 0 * 0，例如 [第一章 Node.js组成和原理](https://theanarkh.github.io/understand-nodejs/chapter01-Node.js%E7%BB%84%E6%88%90%E5%92%8C%E5%8E%9F%E7%90%86/) 中，执行uv_idle_init函数后，Libuv的内存视图未能正确展示

![image](https://github.com/theanarkh/understand-nodejs/assets/36107303/b477527c-e920-40ab-a8b2-7ebd57fa073d)

**Comment by zkk123123** [comment]
您好，您的邮件我已收到，谢谢
——张可可
