### ISSUE TITLE
[Chapter 28] epoll_wait()使进程“挂起”的说法不严谨

### ISSUE THREAD

**Issue by jazelly** [theanarkh/understand-nodejs#32]
> 第二种方式是消费者会把自己挂起，也就是说这个消费所在的进程会被挂起，然后等到有任务的时候，操作系统就会唤醒它，相对来说，这种方式是更高效的，Libuv 里也正是使用这种方式。

我觉得”挂起“的说法来自于process hang，一般指的是阻塞整个进程。
epoll_wait()会让进程进入可打断的休眠 interruptible sleep，并不会让整个进程阻塞，我感觉这一点说清楚比较好以免造成误解。

**Comment by zkk123123** [comment]
您好，您的邮件我已收到，谢谢
——张可可

**Comment by theanarkh** [comment]
interruptible sleep 只是说可以被某些特殊的条件唤醒，比如信号。这时候进程是进入阻塞状态的，在单进程单线程的情况下。

**Comment by jazelly** [comment]
我之前的标题有误，原文出自chapter 28

我有点难以理解的是前文说libuv通过阻塞**进程**的方式等epoll唤醒，后文说libuv通过线程池来解决这个问题。我理解的是线程池解决的是线程阻塞导致进程阻塞的问题，通过引入多个线程来解决，

这里是不是想表达的是
1. 单进程单线程的情况下 epoll会阻断**线程**。
2. 由于是单线程所以进程也在阻塞

因为当我看到
> 第二种方式是消费者会把自己挂起，也就是说这个消费所在的进程会被挂起，然后等到有任务的时候，操作系统就会唤醒它，相对来说，这种方式是更高效的，Libuv 里也正是使用这种方式。

我会联想到每有一个io就把整个进程挂起，这不合理，除非libuv开多个子进程 但那样花销太大了。

**Comment by theanarkh** [comment]
是的，因为 epoll_wait 阻塞的是线程，如果单进程单线程的话就会导致进程阻塞，否则只会阻塞调用 epoll_wait 的线程，文章的前后文的上下文不一样。

**Comment by jazelly** [comment]
感谢指明，我觉得这里最好稍微详细一点，我确实在这看了好久没看懂才raise issue

**Comment by theanarkh** [comment]
这个仓库年久失修了。
