### ISSUE TITLE
拓展nodejs-相关问题

### ISSUE THREAD

**Issue by seriouslym** [theanarkh/understand-nodejs#33]
拓展nodejs最后一步，在/lib/internal/bootstrap/loaders.js中的internalBindingWhitelist数组添加cyb_wrap，我的node版本是v10.24，这个文件里面没有这个数组，应该怎么做呢？
现在报如下错误
![image](https://github.com/user-attachments/assets/9835af8d-922d-4555-b9a5-485de5f70c1d)

**Comment by zkk123123** [comment]
您好，您的邮件我已收到，谢谢
——张可可

**Comment by seriouslym** [comment]
在v10.24 将node.gyp中添加的src/cyb_wrap.cc src/cyb_wrap.h 改为src/cyb.cc  src/cyb.h
loaders.js 中无需改动即可
![image](https://github.com/user-attachments/assets/0d965c58-c833-4c60-987b-8a933682d707)
