### ISSUE TITLE
使用什么IDE打开nodejs源代码?

### ISSUE THREAD

**Issue by anlexN** [theanarkh/understand-nodejs#5]
nodejs源代码有js, c++.

**Comment by jesonxie** [comment]
vscode ?

**Comment by theanarkh** [comment]
vscode可以，可以跳就行

**Comment by theanarkh** [comment]
> nodejs源代码有js, c++.

vscode可以，可以跳就行

**Comment by theanarkh** [comment]
> vscode ?

bingo

**Comment by anlexN** [comment]
我需要Jetbrian Clion打开，可惜有问题。

**Comment by theanarkh** [comment]
> 我需要Jetbrian Clion打开，可惜有问题。

什么问题呢，使用什么ide都可以的

**Comment by anlexN** [comment]
就是不能运行，各种错误。你可以试试Jetbrain Clion.

**Comment by yuzhanglong** [comment]
> 就是不能运行，各种错误。你可以试试Jetbrain Clion.

我两个都用过，首先 clion 可以跑，但是调试 node.js 源码体验没有 vscode 好，例如调试 timers.js 这种内部模块时出现不能跳转到本地代码、函数体经常无法进入等弊端，调试 C++ 代码倒是没有啥问题。目前我没找到解决方案，我平时都是用 jetbrains 的，但在调试 node 源码时还是会使用 vscode。

**Comment by anlexN** [comment]
@yuzhanglong 你的是windows环境运行的吗？

**Comment by yuzhanglong** [comment]
> @yuzhanglong 你的是windows环境运行的吗？

MacBook Pro M1

**Comment by anlexN** [comment]
@yuzhanglong 你试一下windows, 我的是windows, 跑不动。

**Comment by yuzhanglong** [comment]
> @yuzhanglong 你试一下windows, 我的是windows, 跑不动。

用 vscode 的吗？

**Comment by anlexN** [comment]
vscode, jetbrain clion 这啷个软件

**Comment by yuzhanglong** [comment]
> vscode, jetbrain clion 这啷个软件

vs code可以参考我整理的这篇文章https://blog.yuzzl.top/article/how-node-js-works-part-1

**Comment by anlexN** [comment]
很显然 你还是mac环境
请问你能不能自己用windows环境试一下？成功没？
这是我微信：1293006794

**Comment by yuzhanglong** [comment]
> 很显然 你还是mac环境 请问你能不能自己用windows环境试一下？成功没？ 这是我微信：1293006794

可以的，我之前有试过。

**Comment by anlexN** [comment]
之前是多久，现在能不能再试一下？

**Comment by yuzhanglong** [comment]
> 之前是多久，现在能不能再试一下？

抱歉，不能。
