### ISSUE TITLE
希望加一篇 怎样引入v8 头文件的 讲解

### ISSUE THREAD

**Issue by navegador5** [theanarkh/understand-nodejs#9]
很多api 只  include "v8.h" 是用不了的
比如我想利用 v8自带的parser和ast ,
参看d8 的--print-ast 的实现，需要下列头文件
    #include "src/parsing/parse-info.h"
    #include "src/parsing/parser.h"
    #include "src/parsing/parsing.h"
    #include "src/parsing/scanner-character-streams.h"
    #include "src/common/globals.h"
但是我就是引入不了，各种报错什么 builtin generated找不到, torque generated找不到，
我直接用 的node 源码里的v8

**Comment by theanarkh** [comment]
V8的我也不是很熟悉，去问一下相关的人

**Comment by gengjiawen** [comment]
Node.js只暴露了V8公开的API，你要用所有的API，只有引用源码的方式了。

可以尝试引用 https://github.com/bnoordhuis/v8-cmake
